# netlify.toml 

[build]
  command = "export NODE_OPTIONS=--openssl-legacy-provider && yarn generate"
  publish = "site/dist"
  functions = "lambda"

[build.environment]
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--ignore-engines"